title: LispLY's blog
author: 陆遥
email: lisply@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  what ever
# social links
twitter_username: your-twitter-handle
github_username:  LispLY

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
