title: LispLY's blog
author: 陆遥
email: lisply@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  what ever
# social links
twitter_username: your-twitter-handle
github_username:  LispLY

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
